import XCTest
@testable import Shell

final class ClaudeHistoryTests: XCTestCase {
    private let id = "6576c084-4ec9-4841-8363-0966b538fe03"

    private func user(_ text: String, cwd: String = "/Users/me/code/repo", branch: String = "main", extra: String = "") -> String {
        #"{"type":"user","isSidechain":false,\#(extra)"cwd":"\#(cwd)","gitBranch":"\#(branch)","sessionId":"s","message":{"role":"user","content":"\#(text)"}}"#
    }

    private func data(_ lines: [String]) -> Data { Data((lines.joined(separator: "\n") + "\n").utf8) }

    func testTitlePrefersRenameThenAITitleThenFirstPrompt() {
        let date = Date()
        let prompt = data([user("Fix the login bug\\nand add a test")])
        XCTAssertEqual(ClaudeTranscriptIndex.parse(id: id, head: prompt, tail: Data(), modified: date)?.title, "Fix the login bug")

        let ai = data([user("Fix the login bug"), #"{"type":"ai-title","aiTitle":"Login bug fix","sessionId":"s"}"#])
        XCTAssertEqual(ClaudeTranscriptIndex.parse(id: id, head: ai, tail: Data(), modified: date)?.title, "Login bug fix")

        let renamed = data([#"{"type":"custom-title","customTitle":"fix-login","sessionId":"s"}"#, user("Fix the login bug"),
                            #"{"type":"ai-title","aiTitle":"Login bug fix","sessionId":"s"}"#])
        let session = ClaudeTranscriptIndex.parse(id: id, head: renamed, tail: Data(), modified: date)
        XCTAssertEqual(session?.title, "fix-login")
        XCTAssertEqual(session?.prompt, "Fix the login bug")
        XCTAssertEqual(ClaudeTranscriptIndex.parse(id: id, head: prompt, tail: Data(), modified: date)?.prompt, "Fix the login bug")
        XCTAssertEqual(session?.id, id)
        XCTAssertEqual(session?.directory, "/Users/me/code/repo")
        XCTAssertEqual(session?.branch, "main")
        XCTAssertEqual(session?.lastActive, date)
    }

    func testSkipsMetaAndSidechainPromptsAndShowsSlashCommands() {
        let lines = data([
            user("Caveat: generated by the CLI", extra: #""isMeta":true,"#),
            #"{"type":"user","isSidechain":true,"cwd":"/elsewhere","message":{"content":"subagent prompt"}}"#,
            user("<command-name>/review</command-name><command-args>42</command-args>"),
        ])
        let session = ClaudeTranscriptIndex.parse(id: id, head: lines, tail: Data(), modified: Date())
        XCTAssertEqual(session?.title, "/review 42")
        XCTAssertEqual(session?.directory, "/Users/me/code/repo")
    }

    func testTailUpdatesBranchAndTitleButKeepsFirstPrompt() {
        let head = data([user("First prompt"), user("partial line cut off")]).dropLast(10)
        let tail = Data(("…partial\n" + [user("Later prompt", branch: "feature/x"), #"{"type":"ai-title","aiTitle":"Later title"}"#].joined(separator: "\n") + "\n").utf8)
        let session = ClaudeTranscriptIndex.parse(id: id, head: Data(head), tail: tail, modified: Date())
        XCTAssertEqual(session?.branch, "feature/x")
        XCTAssertEqual(session?.title, "Later title")

        let untitled = ClaudeTranscriptIndex.parse(id: id, head: Data(head), tail: Data(("…partial\n" + user("Later prompt") + "\n").utf8), modified: Date())
        XCTAssertEqual(untitled?.title, "First prompt")
    }

    func testDropsEmptyTemporaryAndBadlyNamedSessions() {
        XCTAssertNil(ClaudeTranscriptIndex.parse(id: id, head: data([#"{"type":"bridge-session","sessionId":"s"}"#]), tail: Data(), modified: Date()))
        XCTAssertNil(ClaudeTranscriptIndex.parse(id: id, head: data([user("hi", cwd: "/private/var/folders/x/T/scratch")]), tail: Data(), modified: Date()))
        XCTAssertTrue(ClaudeTranscriptIndex.isTemporary("/tmp/x"))
        XCTAssertFalse(ClaudeTranscriptIndex.isTemporary("/Users/me/code"))
    }

    func testScanListsNewestFirstAndSkipsSubagents() throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        let project = root.appendingPathComponent("-Users-me-code-repo")
        try FileManager.default.createDirectory(at: project.appendingPathComponent(id + "/subagents"), withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }
        let older = "11111111-1111-1111-1111-111111111111"
        try data([user("older")]).write(to: project.appendingPathComponent(older + ".jsonl"))
        try data([user("newer")]).write(to: project.appendingPathComponent(id + ".jsonl"))
        try data([user("subagent")]).write(to: project.appendingPathComponent(id + "/subagents/agent-1.jsonl"))
        try data([user("not a session id")]).write(to: project.appendingPathComponent("notes.jsonl"))
        try FileManager.default.setAttributes([.modificationDate: Date().addingTimeInterval(-3600)],
                                              ofItemAtPath: project.appendingPathComponent(older + ".jsonl").path)

        let index = ClaudeTranscriptIndex(root: root)
        XCTAssertEqual(index.scan().map(\.title), ["newer", "older"])
        // Cached results are reused until the file changes.
        try data([user("newer"), #"{"type":"custom-title","customTitle":"renamed"}"#]).write(to: project.appendingPathComponent(id + ".jsonl"))
        XCTAssertEqual(index.scan().first?.title, "renamed")
    }

    func testResumeCommandOnlyForSessionIDs() {
        let session = ClaudePastSession(id: id, directory: "/tmp", title: "t", prompt: nil, branch: nil, lastActive: Date())
        XCTAssertEqual(PastSessionAction.command(for: .resume, session: session), "claude --resume \(id)")
        XCTAssertEqual(PastSessionAction.command(for: .newSession, session: session), "claude")
        XCTAssertNil(PastSessionAction.command(for: .terminal, session: session))
        var bad = session
        bad.id = "x; rm -rf ~"
        XCTAssertNil(PastSessionAction.command(for: .resume, session: bad))
    }

    @MainActor
    func testButtonVisibilityModes() {
        XCTAssertTrue(DashboardVisibility.shows(mode: .always, sessions: 0, claudeInstalled: true, dashboardOpen: false))
        XCTAssertFalse(DashboardVisibility.shows(mode: .always, sessions: 0, claudeInstalled: false, dashboardOpen: false))
        XCTAssertFalse(DashboardVisibility.shows(mode: .whenActive, sessions: 0, claudeInstalled: true, dashboardOpen: false))
        XCTAssertTrue(DashboardVisibility.shows(mode: .whenActive, sessions: 2, claudeInstalled: true, dashboardOpen: false))
        XCTAssertFalse(DashboardVisibility.shows(mode: .never, sessions: 2, claudeInstalled: true, dashboardOpen: false))
        XCTAssertTrue(DashboardVisibility.shows(mode: .never, sessions: 0, claudeInstalled: false, dashboardOpen: true))
    }

    func testOldDashboardToggleMigrates() {
        var merged: [String: Any] = ["claudeSessionsButton": "always", "claudeDashboard": false]
        SettingsStore.migrate(stored: ["claudeDashboard": false], into: &merged)
        XCTAssertEqual(merged["claudeSessionsButton"] as? String, "never")
        XCTAssertNil(merged["claudeDashboard"])

        merged = ["claudeSessionsButton": "always"]
        SettingsStore.migrate(stored: ["claudeDashboard": true], into: &merged)
        XCTAssertEqual(merged["claudeSessionsButton"] as? String, "always")

        merged = ["claudeSessionsButton": "whenActive"]
        SettingsStore.migrate(stored: ["claudeDashboard": false, "claudeSessionsButton": "whenActive"], into: &merged)
        XCTAssertEqual(merged["claudeSessionsButton"] as? String, "whenActive")
    }
}
