import AppKit
import Observation

/// Tracks the effective appearance and active theme, and regenerates the
/// libghostty configuration whenever settings or the system appearance change.
@MainActor
@Observable
final class ConfigController {
    static let shared = ConfigController()

    private(set) var isDark = true
    private(set) var theme: TerminalTheme = .shellDark

    @ObservationIgnored private var appearanceObservation: NSKeyValueObservation?
    @ObservationIgnored private var reloadWork: DispatchWorkItem?
    /// The config text last written to disk.
    @ObservationIgnored private var lastConfig: String?

    static var configURL: URL { SettingsStore.supportDirectory.appendingPathComponent("ghostty.conf") }

    private init() {}

    func start() {
        applyAppAppearance()
        recompute()
        writeConfig()

        appearanceObservation = NSApp.observe(\.effectiveAppearance, options: [.new]) { _, _ in
            DispatchQueue.main.async {
                MainActor.assumeIsolated { ConfigController.shared.appearanceChanged() }
            }
        }
        SettingsStore.shared.observe { old, new in
            MainActor.assumeIsolated { ConfigController.shared.settingsChanged(old: old, new: new) }
        }
    }

    private func settingsChanged(old: AppSettings, new: AppSettings) {
        if old.appearance != new.appearance { applyAppAppearance() }
        recompute()
        // Many settings are UI state (sidebar tab, explorer width, pickers).
        // Only reload libghostty, which reconfigures every surface, when the
        // generated config actually changes.
        guard Self.generate(settings: new, theme: theme) != lastConfig else { return }
        scheduleReload()
    }

    private func appearanceChanged() {
        let wasDark = isDark
        recompute()
        GhosttyRuntime.shared.applyColorScheme(NSApp.effectiveAppearance)
        if wasDark != isDark { scheduleReload() }
    }

    private func applyAppAppearance() {
        switch SettingsStore.shared.settings.appearance {
        case .system: NSApp.appearance = nil
        case .light: NSApp.appearance = NSAppearance(named: .aqua)
        case .dark: NSApp.appearance = NSAppearance(named: .darkAqua)
        }
    }

    private func recompute() {
        let dark = NSApp.effectiveAppearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua
        if dark != isDark { isDark = dark }
        // Assign only on change so views reading `theme` don't re-render.
        let resolved = ThemeLibrary.shared.resolved(dark: dark, settings: SettingsStore.shared.settings)
        if resolved != theme { theme = resolved }
        AppIcon.update()
    }

    /// Reapplies the theme after the theme library finishes loading.
    func themesLoaded() {
        let old = theme
        recompute()
        if old != theme { scheduleReload() }
    }

    private func scheduleReload() {
        reloadWork?.cancel()
        let work = DispatchWorkItem {
            MainActor.assumeIsolated {
                ConfigController.shared.writeConfig()
                GhosttyRuntime.shared.reload(configPath: ConfigController.configURL.path)
            }
        }
        reloadWork = work
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.05, execute: work)
    }

    func writeConfig() {
        let text = Self.generate(settings: SettingsStore.shared.settings, theme: theme)
        lastConfig = text
        try? text.write(to: Self.configURL, atomically: true, encoding: .utf8)
    }

    static func generate(settings s: AppSettings, theme t: TerminalTheme) -> String {
        var lines: [String] = [
            "# Generated by Shell from settings.json. Edits here are overwritten.",
            "# Add custom Ghostty options in Settings › Advanced instead.",
            "",
        ]
        func set(_ key: String, _ value: CustomStringConvertible) { lines.append("\(key) = \(value)") }

        // Text
        if !s.fontFamily.isEmpty { set("font-family", s.fontFamily) }
        set("font-size", String(format: "%.1f", s.fontSize))
        if s.lineHeight != 1.0 { set("adjust-cell-height", "\(Int(((s.lineHeight - 1) * 100).rounded()))%") }
        if s.letterSpacing != 1.0 { set("adjust-cell-width", "\(Int(((s.letterSpacing - 1) * 100).rounded()))%") }
        if !s.ligatures {
            set("font-feature", "-calt")
            set("font-feature", "-liga")
            set("font-feature", "-dlig")
        }
        set("font-thicken", s.fontThicken)

        // Colors
        set("background", t.background.hex)
        set("foreground", t.foreground.hex)
        for (i, c) in t.palette.enumerated() { set("palette", "\(i)=\(c.hex)") }
        if let c = t.cursor { set("cursor-color", c.hex) }
        if let c = t.cursorText { set("cursor-text", c.hex) }
        if let c = t.selectionBackground { set("selection-background", c.hex) }
        if let c = t.selectionForeground { set("selection-foreground", c.hex) }
        set("minimum-contrast", String(format: "%.1f", max(1, s.minimumContrast)))
        set("background-opacity", String(format: "%.2f", s.backgroundOpacity))
        if s.backgroundBlur && s.backgroundOpacity < 1 { set("background-blur", 20) }

        // Cursor
        set("cursor-style", s.cursorStyle.rawValue)
        set("cursor-style-blink", s.cursorBlink)

        // Window/terminal behavior
        set("window-padding-x", s.paddingX)
        set("window-padding-y", s.paddingY)
        set("window-padding-balance", true)
        set("window-padding-color", "extend")
        set("unfocused-split-opacity", s.dimUnfocusedSplits ? "0.8" : "1")
        set("scrollback-limit-bytes", max(1, s.scrollbackMB) * 1_000_000)
        set("copy-on-select", s.copyOnSelect ? "clipboard" : "false")
        set("macos-option-as-alt", s.optionKey.rawValue)
        set("mouse-hide-while-typing", s.hideMouseWhileTyping)
        set("clipboard-paste-protection", s.pasteProtection)
        set("clipboard-read", "ask")
        set("clipboard-write", "allow")
        set("focus-follows-mouse", s.focusFollowsMouse)
        set("confirm-close-surface", true)
        set("link-url", true)
        set("desktop-notifications", true)
        set("right-click-action", "context-menu")

        // Shell integration: Shell injects Ghostty's zsh integration itself
        // (see Resources/shell/zsh) so both can coexist.
        set("shell-integration", "none")
        set("shell-integration-features", "no-cursor,sudo,title,ssh-env,no-path")
        if !s.shellPath.isEmpty { set("command", s.shellPath) }

        // Keybindings: app shortcuts live in the menu bar. Ghostty only gets
        // terminal-level key mappings used when typing directly into the PTY.
        set("keybind", "clear")
        if s.naturalTextEditing {
            for (trigger, action) in naturalTextEditing { set("keybind", "\(trigger)=\(action)") }
        }
        set("keybind", "shift+enter=text:\\x1b\\r")

        if !s.extraGhosttyConfig.isEmpty {
            lines.append("")
            lines.append("# Advanced (from Settings)")
            lines.append(s.extraGhosttyConfig)
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// iTerm2's "Natural Text Editing" preset.
    static let naturalTextEditing: [(String, String)] = [
        ("alt+arrow_left", "esc:b"),
        ("alt+arrow_right", "esc:f"),
        ("super+arrow_left", "text:\\x01"),
        ("super+arrow_right", "text:\\x05"),
        ("alt+backspace", "text:\\x1b\\x7f"),
        ("super+backspace", "text:\\x15"),
        ("alt+delete", "esc:d"),
        ("super+delete", "text:\\x0b"),
    ]
}
